// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaxbIBvkpAxHNm3zPei3y1OuzuX2YCAEk',
    appId: '1:412008010823:web:b5920b44338367cf978d62',
    messagingSenderId: '412008010823',
    projectId: 'sportsync-376d7',
    authDomain: 'sportsync-376d7.firebaseapp.com',
    storageBucket: 'sportsync-376d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9VxrmU4INEDfj22i67e9w8-RrfivH9wI',
    appId: '1:412008010823:android:01406ae829a3ed48978d62',
    messagingSenderId: '412008010823',
    projectId: 'sportsync-376d7',
    storageBucket: 'sportsync-376d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARBBmcVXbgKxH24CAGOAeuaktdf6UTiY0',
    appId: '1:412008010823:ios:221babb1ffdd058b978d62',
    messagingSenderId: '412008010823',
    projectId: 'sportsync-376d7',
    storageBucket: 'sportsync-376d7.firebasestorage.app',
    iosBundleId: 'com.sportsync.sportsync',
  );

}