const List<Map<String, dynamic>> courtsData = [
  {
    'id': 'c1',
    'name': 'Smash Ville Fitness Center',
    'type': 'Badminton',
    'price': 350,
    'rating': 4.8,
    'location': '31 T.Monteverde St, Poblacion District, Davao City',
    'phone': '+63 82 221 1234',
    'numberOfCourts': 12,
    'amenities': ['Locker Rooms', 'Pro Shop', 'Cafe'],
    'coordinates': {'lat': 7.0738, 'lng': 125.6206},
  },
  {
    'id': 'c2',
    'name': 'MTS Pickleball Courts',
    'type': 'Pickleball',
    'price': 300,
    'rating': 4.6,
    'location': 'Matina Town Square, Talomo, Davao City',
    'phone': '+63 82 297 5678',
    'numberOfCourts': 6,
    'amenities': ['Equipment Rental', 'Water Station'],
    'coordinates': {'lat': 7.0644, 'lng': 125.5967},
  },
  {
    'id': 'c3',
    'name': 'Evergold Recreation Center',
    'type': 'Basketball',
    'price': 400,
    'rating': 4.9,
    'location': 'Iñigo St, Obrero, Davao City',
    'phone': '+63 82 225 9012',
    'numberOfCourts': 2,
    'amenities': ['Showers', 'Bleachers', 'Scoreboard'],
    'coordinates': {'lat': 7.0875, 'lng': 125.6137},
  },
  {
    'id': 'c4',
    'name': 'Badminton World',
    'type': 'Badminton',
    'price': 350,
    'rating': 4.7,
    'location': 'Avanceña St, Poblacion District, Davao City',
    'phone': '+63 82 224 3456',
    'numberOfCourts': 10,
    'amenities': ['Coach available', 'Parking'],
    'coordinates': {'lat': 7.0771, 'lng': 125.6032},
  },
  {
    'id': 'c5',
    'name': 'Crisron Pickle Ball Court',
    'type': 'Pickleball',
    'price': 250,
    'rating': 4.5,
    'location': '168 Don Julian Rodriguez Sr. Ave, Talomo, Davao City',
    'phone': '+63 82 298 7890',
    'numberOfCourts': 8,
    'amenities': ['Benches', 'Night Lighting'],
    'coordinates': {'lat': 7.0993, 'lng': 125.5787},
  },
];
